package simplegs.session;

public enum SessionAttribute {
	USERINFO, 
	USERID, 
	COMMAND_STATE, 
	TIMESTAMP, 
	EVENT_OBJECT, 
	FIRST_LOGIN, 
	LAST_ERROR_MESSAGE, 
	CURRENT_MAP_OBJECT,
	ATTACK_COUNT,
	IN_BATTLE,
	SKILL_DROP_CARGO,
	SKILL_DROP_SHIP_ID,
	PREVIOUSCMD,
	SHADOW_USER_INFO,
	SHADOW_PVP_FLEET_ID,	
	SHADOW_PVP_RETRY_WAIT,
	SHADOW_PVP_CASH,
}
